featureName=BoberKurwa IDE
providerName=BoberKurwa Corp
description=BoberKurwa IDE (Eclipse plugin)
copyright=\u00A9 2010-2024, BoberKurwa Corp
licenseURL=https://dbeaver.io/product/dbeaver_license.txt
