featureName=BoberKurwa Databases UI
providerName=BoberKurwa Corp
description=BoberKurwa SQL databases UI
copyright=\u00A9 2010-2024, BoberKurwa Corp
licenseURL=https://dbeaver.io/product/dbeaver_license.txt
