featureName=BoberKurwa Databases
providerName=BoberKurwa Corp
description=BoberKurwa SQL databases support
copyright=\u00A9 2010-2024, BoberKurwa Corp
licenseURL=https://dbeaver.io/product/dbeaver_license.txt
