featureName=BoberKurwa Desktop UI Test Components
providerName=BoberKurwa Corp
description=BoberKurwa Desktop UI Test
copyright=\u00A9 2010-2024, BoberKurwa Corp
licenseURL=https://dbeaver.io/product/dbeaver_license.txt

