packageName=dbeaver
appName=BoberKurwa
appTitle=BoberKurwa
productEclipseId=org.jkiss.dbeaver.core.appstore
productModifier=ce
productType=community
productName=BoberKurwa CE
productBrandText=Universal Database Manager
productDescription=Universal Database Manager and SQL Client
productTrademark=BoberKurwa is a trademark of BoberKurwa Corp
productCopyright=BoberKurwa Corp
productEmail=support@dbeaver.com
productCompany=BoberKurwa Corp
productWebSite=https://dbeaver.io/
productBundleId=org.jkiss.dbeaver.core.appstore
